### ISSUE TITLE
Attribute names iOS (snake_case)

### ISSUE THREAD

**Issue by enisze** [customerio/customerio-expo-plugin#85]
Hey,

I would like to disable the option that attributes are always send in snake_case on iOS:
<img width="637" alt="image" src="https://github.com/customerio/customerio-expo-plugin/assets/15271433/e8597209-aa19-46da-b229-ba3818fdb90e">

How can I achieve this? 
Kind regards,
Enis

**Comment by mrehan27** [comment]
Hi @enisze Could you please let us know the version of the `customerio-reactnative` package you are currently using with Expo? We encountered a [bug in the iOS SDK previously, but it has been fixed](https://customer.io/docs/sdk/react-native/migrate-upgrade/#we-fixed-a-bug-in-our-ios-modules-that-may-impact-your-data) now. To benefit from the fix, you need to update your React Native package. By doing so, the issue should be resolved. It's important to note that data reported using newer versions of the SDK will not automatically convert to snake case unless sent explicitly.

If you have any further questions or need assistance with the update process, please don't hesitate to reach out to us.

**Comment by enisze** [comment]
Hey, sure @mrehan27. I already saw this and updated to:

```
    "customerio-expo-plugin": "1.0.0-beta.10",
    "customerio-reactnative": "2.4.2",
```

But still having this issue with iOS using the expo-plugin

**Comment by mrehan27** [comment]
Sorry for any inconvenience that you've experienced. To assist you further, could you please provide the specific code snippet or exact key used for tracking the User ID? Additionally, can you please [capture logs](https://www.customer.io/docs/sdk/ios/troubleshooting/#capture-logs) during the tracking process and share with us.

Please make sure to remove any sensitive data from code/logs you share. You can also email us these details at  win@customer.io, mentioning your Github ticket in the email.

Please let us know if there's anything else we can assist you with.

**Comment by enisze** [comment]
Hey @mrehan27 the issue seems to be fixed now :) I has to really create a new build. Just using expo update did not work
